server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://140.143.156.27:3306/leyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: GLBglb582@@
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.154.130
  redis:
    host: 192.168.154.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    ip-address: 127.0.0.1