ly:
  jwt:
    pubKeyPath: D:/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.154.130
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1