spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.154.130
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.154.130
server:
  port: 8086
leyou:
  sms:
    accessKeyId: LTAI4G5PWhF9Qb9ZWQ2YBZca # 你自己的accessKeyId
    accessKeySecret: kuW3l6ZcLONTkD3shron9t6XukE42y # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_203725516 # 模板名称
